#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
binary="$(mktemp /tmp/hp2000-keyboard.XXXXXX)"
trap 'rm -f "$binary"' EXIT
g++ -std=c++17 -Wall -Wextra -Werror -pthread -Itests/file-stubs src/services/DownloadService.cpp tests/download_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Werror -Itests/file-stubs src/services/FileBridge.cpp src/services/ShellParser.cpp tests/file_bridge_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Werror src/services/Calculator.cpp src/services/ShellParser.cpp tests/new_models_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Werror -Itests/stubs src/input/Keyboard.cpp tests/audio_control_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Werror tests/radio_memory_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Werror src/services/ClassicNDEF.cpp src/services/NDEFCodec.cpp tests/classic_ndef_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Werror tests/nfc_polling_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Werror -Itests/buzzer-stubs src/modules/Buzzer.cpp tests/buzzer_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Werror src/games/ArcadeModels.cpp tests/arcade_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Werror src/games/GameModels.cpp src/games/ArcadeModels.cpp tests/games_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Werror -Itests/stubs src/input/Keyboard.cpp tests/keyboard_test.cpp -o "$binary"
"$binary"

g++ -std=c++17 -Wall -Wextra -Werror src/services/NDEFCodec.cpp src/services/ScriptParser.cpp tests/codec_test.cpp -o "$binary"
"$binary"

g++ -std=c++17 -Wall -Wextra -Wno-missing-field-initializers -Itests/display-stubs src/games/ArcadeModels.cpp src/services/Calculator.cpp src/ui/KeyboardModel.cpp src/ui/DisplayManager.cpp src/ui/GameRenderer.cpp src/ui/Theme.cpp tests/display_test.cpp -o "$binary"
"$binary"
g++ -std=c++17 -Wall -Wextra -Wno-missing-field-initializers -Itests/display-stubs src/games/ArcadeModels.cpp src/services/Calculator.cpp src/ui/KeyboardModel.cpp src/ui/DisplayManager.cpp src/ui/GameRenderer.cpp src/ui/Theme.cpp src/ui/UI.cpp tests/ui_test.cpp -o "$binary"
"$binary"

g++ -std=c++17 -Wall -Wextra -Wno-missing-field-initializers -Itests/display-stubs src/games/ArcadeModels.cpp src/services/Calculator.cpp src/ui/KeyboardModel.cpp src/ui/DisplayManager.cpp src/ui/GameRenderer.cpp src/ui/Theme.cpp tests/game_render_test.cpp -o "$binary"
"$binary"

media_decoder_object="$(mktemp /tmp/dmt-jpeg.XXXXXX.o)"
gcc -std=c11 -O2 -Wall -Wextra -c src/third_party/tjpgd/tjpgd.c -o "$media_decoder_object"
g++ -std=c++17 -O2 -Wall -Wextra -Werror src/media/MediaDecoder.cpp tests/media_test.cpp "$media_decoder_object" -o "$binary"
"$binary"
rm -f "$media_decoder_object"
media_decoder_object="$(mktemp /tmp/dmt-jpeg.XXXXXX.o)"
gcc -std=c11 -O2 -Wall -Wextra -c src/third_party/tjpgd/tjpgd.c -o "$media_decoder_object"
g++ -std=c++17 -O2 -Wall -Wextra -Wno-missing-field-initializers -Itests/display-stubs src/games/ArcadeModels.cpp src/services/Calculator.cpp src/ui/KeyboardModel.cpp src/ui/DisplayManager.cpp src/ui/GameRenderer.cpp src/ui/Theme.cpp src/media/MediaDecoder.cpp tests/media_display_test.cpp "$media_decoder_object" -o "$binary"
"$binary"
rm -f "$media_decoder_object"
g++ -std=c++17 -Wall -Wextra -Werror tests/ble_scan_test.cpp -o "$binary"
"$binary"
