from PikaObj import *
def button() -> str: ...
def pressed() -> str: ...
def sleep_ms(ms: int): ...
def millis() -> int: ...
def alive() -> int: ...
def title(text: str): ...
def label(text: str) -> int: ...
def button_widget(text: str) -> int: ...
def set_text(id: int, text: str): ...
def selected() -> int: ...
def rectangle(x1: int, y1: int, x2: int, y2: int, color: int) -> int: ...
def clear_canvas(): ...
def width() -> int: ...
def height() -> int: ...
def ir_nec(address: int, command: int, repeats: int) -> int: ...
def beep(frequency: int, duration: int): ...
def read_text(path: str) -> str: ...
def write_text(path: str, text: str) -> int: ...
def append_text(path: str, text: str) -> int: ...
def listdir(path: str) -> str: ...
def mkdir(path: str) -> int: ...
def remove(path: str) -> int: ...
def destroy(): ...
