#pragma once
static const char hp_tkinter_source[] =
"# Compact TFT adapter. This is not desktop Tcl/Tk.\n"
"import device\n"
"\n"
"class Event:\n"
"    def __init__(self, key):\n"
"        self.keysym = key\n"
"\n"
"class Tk:\n"
"    def __init__(self):\n"
"        self.running = True\n"
"        self.handlers = {}\n"
"        self.actions = {}\n"
"        self.timer = None\n"
"        self.deadline = 0\n"
"    def title(self, text):\n"
"        device.title(text)\n"
"    def bind(self, key, callback):\n"
"        self.handlers[key] = callback\n"
"    def after(self, ms, callback):\n"
"        self.deadline = device.millis() + ms\n"
"        self.timer = callback\n"
"    def update(self):\n"
"        key = device.button()\n"
"        if key != \"\":\n"
"            names = {\"UP\":\"<Up>\",\"DOWN\":\"<Down>\",\"LEFT\":\"<Left>\",\"RIGHT\":\"<Right>\",\"OK\":\"<Return>\"}\n"
"            event = Event(key)\n"
"            if \"<Key>\" in self.handlers:\n"
"                callback = self.handlers[\"<Key>\"]\n"
"                callback(event)\n"
"            if names[key] in self.handlers:\n"
"                callback = self.handlers[names[key]]\n"
"                callback(event)\n"
"            if key == \"OK\":\n"
"                selected = device.selected()\n"
"                if str(selected) in self.actions:\n"
"                    callback = self.actions[str(selected)]\n"
"                    callback()\n"
"        if self.timer != None:\n"
"            if device.millis() >= self.deadline:\n"
"                callback = self.timer\n"
"                self.timer = None\n"
"                callback()\n"
"    def mainloop(self):\n"
"        while self.running and device.alive():\n"
"            self.update()\n"
"            device.sleep_ms(20)\n"
"    def destroy(self):\n"
"        self.running = False\n"
"        device.destroy()\n"
"\n"
"class Label:\n"
"    def __init__(self, master, text=\"\"):\n"
"        self.id = device.label(text)\n"
"    def pack(self):\n"
"        pass\n"
"    def config(self, text):\n"
"        device.set_text(self.id, text)\n"
"    def configure(self, text):\n"
"        self.config(text)\n"
"\n"
"class Button:\n"
"    def __init__(self, master, text=\"\", command=None):\n"
"        self.id = device.button_widget(text)\n"
"        if command != None:\n"
"            master.actions[str(self.id)] = command\n"
"    def pack(self):\n"
"        pass\n"
"    def config(self, text):\n"
"        device.set_text(self.id, text)\n"
"\n"
"class Canvas:\n"
"    def __init__(self, master, width=0, height=0):\n"
"        self.width = device.width()\n"
"        self.height = device.height()\n"
"    def pack(self):\n"
"        pass\n"
"    def create_rectangle(self, x1, y1, x2, y2, fill=\"white\"):\n"
"        colors = {\"black\":0,\"white\":65535,\"red\":63488,\"green\":2016,\"blue\":31,\"yellow\":65504,\"cyan\":2047,\"magenta\":63519}\n"
"        if fill in colors:\n"
"            color = colors[fill]\n"
"        else:\n"
"            rgb = int(fill[1:], 16)\n"
"            color = ((rgb >> 19) << 11) | (((rgb >> 10) & 63) << 5) | ((rgb >> 3) & 31)\n"
"        return device.rectangle(x1, y1, x2, y2, color)\n"
"    def delete(self, tag):\n"
"        device.clear_canvas()\n"
;
